## Model Architecture

single neuron(i.e perceptron) with 5 input features , which applies sigmoid fxn and generates a single output


In [4]:
#----> create the model class

import torch
import torch.nn as nn

class perceptron_model(nn.Module):   # Must inherit the nn.Module class inorder to use "nn module"

    # constructor
    def __init__(self,num_features):

        #----> invoking the parent class(nn.module) constructor using super keyword

        super().__init__()

        #----> Creating neural network (i.e perceptron)
        self.linear = nn.Linear(num_features,1)  #Accepts 2 paramaters , (numer_of_input_features , number_of_outputs)

        #----> Creating activation function
        self.sigmoid = nn.Sigmoid()

    #----> forward pass:
    def forward(self,features):
      out = self.linear(features)  #passing the features to the linear network (i.e calculates z= wx+b)
      out = self.sigmoid(out)
      return out








## Creating a fake *dataset*

In [5]:
#----> create a dataset
feature = torch.rand(10,5) # dataset with 10 rows and 5 columns

# ----> Create a model
model = perceptron_model(feature.shape[1])

# ----> call model for forward pass
model.forward(feature)  # or better approach to call the forward function is : model(feature)

tensor([[0.5623],
        [0.5624],
        [0.5061],
        [0.5046],
        [0.5624],
        [0.4903],
        [0.4931],
        [0.5087],
        [0.4651],
        [0.5667]], grad_fn=<SigmoidBackward0>)

### passed 10 rows of inputs and we got 10 correspodning output i.e **y_pred**

In [7]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0307, -0.4135,  0.1643,  0.2191,  0.2168]], requires_grad=True)

In [8]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.0414], requires_grad=True)

# To visualize the entire network

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary

summary(model, input_size=feature.shape) #Input size is no_of_rows and columns

Layer (type:depth-idx)                   Output Shape              Param #
perceptron_model                         [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00