In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [2]:
if torch.cuda.is_available():
    print("Gpu available")
    print(torch.cuda.get_device_name(0))
else:
  print('GPU not availble')

Gpu available
Tesla T4


# Ways of Creating Tensors

In [3]:
# Using empty :
#-> Creates a tensor of specified shape in the meomry and returns the pre-existing values in that memory space
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# using zeros
#-> Creates a tensor of specified shape and initializes with all zero values
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# using ones
#-> Creates a tensor of specified shape and initializes with all ones values
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# Using rand
#-> Creates a tensor of specified shape and initializes with all random values each time/runned with different values
torch.rand(3,4)

tensor([[0.1775, 0.4541, 0.3675, 0.3146],
        [0.9035, 0.8875, 0.6236, 0.1755],
        [0.9490, 0.1366, 0.3294, 0.0672]])

In [7]:
# Use of manual_seed
torch.manual_seed(10)
torch.rand(3,4)
#-> Creates a tensor of specified shape and initializes with all random values but each time/run with same values (for reproducability and debugging)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [8]:
# Using tensor
#-> Creates a custom tensors of specified shape where values can we manually defined
torch.tensor([[1,2,3],
              [3,5,7]])

tensor([[1, 2, 3],
        [3, 5, 7]])

In [9]:
# Uing full
#-> Creates a custom tensors of with specified shape(3,4) where all values are fulled with specified value(5)
torch.full((3,4),5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

# Finding the shapes of tensors

In [10]:
a = torch.tensor([[1,3,4],
                  [5,6,7],
                  ])
a.shape

torch.Size([2, 3])

In [11]:
type(a)

torch.Tensor

# To copy the shape of the existing tensor

In [12]:
#-> Copies the shape of tensor 'a' i.e (2,3) and creates a new tensor of (2,3) but with different values
torch.empty_like(a)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3906369341865747556]])

In [13]:
#-> Copies the shape of tensor 'a' i.e (2,3) and creates a new tensor of (2,3) but with all zeroes value
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
#-> Copies the shape of tensor 'a' i.e (2,3) and creates a new tensor of (2,3) but with all ones value
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.rand_like(a)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

###### Problem with above code is that out tensor 'a' if of int datatype but rand() fxn creates a tensor with floatdata type . so we need to explecitly tell the datatype as float

In [16]:
#-> Copies the shape of tensor 'a' i.e (2,3) and creates a new tensor of (2,3) but with all random value each time runned

torch.rand_like(a,dtype=torch.float32)

tensor([[0.7041, 0.5573, 0.6959],
        [0.9849, 0.2924, 0.4823]])

In [17]:
#-> Copies the shape of tensor 'a' i.e (2,3) and creates a new tensor of (2,3) but with all random value each time with same values

torch.manual_seed(10)
torch.rand_like(a,dtype=torch.float32)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

# Finding the datatypes of tensors

In [18]:
print(a)
print('data types of tensor: ',a.dtype)

tensor([[1, 3, 4],
        [5, 6, 7]])
data types of tensor:  torch.int64


# Creating a tensor with specified data type


In [19]:
# creating a tensor with specified data type
torch.tensor([1.9,1.2,2.4],dtype=torch.int32)

tensor([1, 1, 2], dtype=torch.int32)

In [20]:
# creating a tensor with specified data type
torch.tensor([[1,2,5],[6,3,4]],dtype=torch.float32)

tensor([[1., 2., 5.],
        [6., 3., 4.]])

# Converting the data type of existing tensor


In [21]:
# converting the data type of existing tensor
a.to(dtype=torch.float32)

tensor([[1., 3., 4.],
        [5., 6., 7.]])

In [22]:
a

tensor([[1, 3, 4],
        [5, 6, 7]])

# Mathematicla opertaions on tensors

### 1. Scalar Operation

In [23]:
x=torch.rand(2,2)
x

tensor([[0.6938, 0.9693],
        [0.6178, 0.3304]])

In [24]:
# Addition
x+2

tensor([[2.6938, 2.9693],
        [2.6178, 2.3304]])

In [25]:
# Substraction
x-1

tensor([[-0.3062, -0.0307],
        [-0.3822, -0.6696]])

In [26]:
# Multiplication
x*2

tensor([[1.3876, 1.9386],
        [1.2356, 0.6607]])

In [27]:
# Division
x/2

tensor([[0.3469, 0.4847],
        [0.3089, 0.1652]])

In [28]:
# Mod
x%0.3

tensor([[0.0938, 0.0693],
        [0.0178, 0.0304]])

In [29]:
# Power
x**2

tensor([[0.4814, 0.9396],
        [0.3817, 0.1091]])

# 2.Element Wise Operation

In [30]:
a= torch.rand(2,3)
b= torch.rand(2,3)

In [31]:
print(a)
print(b)

tensor([[0.5479, 0.4440, 0.7041],
        [0.5573, 0.6959, 0.9849]])
tensor([[0.2924, 0.4823, 0.6150],
        [0.4967, 0.4521, 0.0575]])


In [32]:
# Add
a+b

tensor([[0.8403, 0.9263, 1.3191],
        [1.0540, 1.1480, 1.0424]])

In [33]:
#Substract
a-b

tensor([[ 0.2556, -0.0384,  0.0891],
        [ 0.0605,  0.2437,  0.9274]])

In [34]:
# Multiplication
a*b

tensor([[0.1602, 0.2141, 0.4330],
        [0.2768, 0.3146, 0.0567]])

In [35]:
#divison
a/b

tensor([[ 1.8741,  0.9205,  1.1449],
        [ 1.1218,  1.5391, 17.1241]])

In [36]:
#power
a**b

tensor([[0.8387, 0.6759, 0.8059],
        [0.7479, 0.8488, 0.9991]])

In [37]:
#Mod
a % b

tensor([[0.2556, 0.4440, 0.0891],
        [0.0605, 0.2437, 0.0071]])

In [38]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [39]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [41]:
d= torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [42]:
#ROUND
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [44]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [46]:
#clamp
#-> Brings the value in a range , value smaller than min will become min and value grater than max will become max
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3. Reduction Operation

###### reduces the entire tensor into a single value

In [47]:
e = torch.randint(size=(2,3),low=0,high=4,dtype=torch.float32)
e

tensor([[0., 0., 3.],
        [3., 2., 0.]])

In [48]:
#sum
# -> sum of entire tensor
torch.sum(e)

tensor(8.)

In [49]:
#sum along column
torch.sum(e,dim=0)

tensor([3., 2., 3.])

In [50]:
# sum along rows
torch.sum(e,dim=1)

tensor([3., 5.])

In [51]:
# mean
torch.mean(e)

tensor(1.3333)

In [52]:
# mean along column
torch.mean(e,dim=0)

tensor([1.5000, 1.0000, 1.5000])

In [53]:
# mean along row
torch.mean(e,dim=1)

tensor([1.0000, 1.6667])

In [54]:
# median
torch.median(e)

tensor(0.)

In [55]:
# max and min
torch.min(e)

tensor(0.)

In [56]:
torch.max(e)

tensor(3.)

In [57]:
# product
# -> multiplies all element of the tensor
torch.prod(e)

tensor(0.)

In [58]:
# standard dev
torch.std(e)

tensor(1.5055)

In [59]:
# variance
torch.var(e)

tensor(2.2667)

In [60]:
# argmax
torch.argmax(e)

tensor(2)

In [61]:
# argmin
torch.argmin(e)

tensor(0)

# 4. Matrix operation

In [62]:
f = torch.randint(size=(2,3),low=0,high=4,dtype=torch.float32)
g = torch.randint(size=(3,2),low=0,high=4,dtype=torch.float32)

In [63]:
print(f)
print(g)

tensor([[3., 2., 2.],
        [1., 0., 0.]])
tensor([[2., 1.],
        [3., 2.],
        [1., 1.]])


In [64]:
# Matrix multiplication
torch.matmul(f,g)

tensor([[14.,  9.],
        [ 2.,  1.]])

# 5. Vector operation

In [65]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [66]:
torch.dot(vector1,vector2)

tensor(32)

In [67]:
f

tensor([[3., 2., 2.],
        [1., 0., 0.]])

In [68]:
# Transpose of matric
torch.transpose(f,1,0)

tensor([[3., 1.],
        [2., 0.],
        [2., 0.]])

In [69]:
# Determinant
g = torch.randint(size=(3,3),low=0,high=4,dtype=torch.float32)
g

tensor([[1., 3., 1.],
        [2., 1., 0.],
        [2., 2., 2.]])

In [70]:
torch.det(g)

tensor(-8.0000)

In [71]:
#Inverse
torch.inverse(g)

tensor([[-2.5000e-01,  5.0000e-01,  1.2500e-01],
        [ 5.0000e-01,  1.4901e-08, -2.5000e-01],
        [-2.5000e-01, -5.0000e-01,  6.2500e-01]])

# 6. Comparison operation

In [72]:
# Grater than
e>f

tensor([[False, False,  True],
        [ True,  True, False]])

In [73]:
# Less than
e<f

tensor([[ True,  True, False],
        [False, False, False]])

In [74]:
#equal to
e==f

tensor([[False, False, False],
        [False, False,  True]])

In [75]:
# not equal to
e!=f

tensor([[ True,  True,  True],
        [ True,  True, False]])

In [76]:
# Greater than equals to
e>=f

tensor([[False, False,  True],
        [ True,  True,  True]])

# 7. Special Functions

In [77]:
k = torch.randint(size=(2,3),low=0,high=4,dtype=torch.float32)
k

tensor([[1., 0., 1.],
        [3., 1., 0.]])

In [78]:
# Log
torch.log(k)

tensor([[0.0000,   -inf, 0.0000],
        [1.0986, 0.0000,   -inf]])

In [79]:
# Exp
torch.exp(k)

tensor([[ 2.7183,  1.0000,  2.7183],
        [20.0855,  2.7183,  1.0000]])

In [80]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 0.0000, 1.0000],
        [1.7321, 1.0000, 0.0000]])

In [81]:
# Sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.5000, 0.7311],
        [0.9526, 0.7311, 0.5000]])

In [82]:
# Softmax
torch.softmax(k,dim=0)

tensor([[0.1192, 0.2689, 0.7311],
        [0.8808, 0.7311, 0.2689]])

In [83]:
#relu
torch.relu(k)

tensor([[1., 0., 1.],
        [3., 1., 0.]])

# Inplace **Operations**

In [84]:
m = torch.randint(size=(2,3),low=1,high=5)
n = torch.randint(size=(2,3),low=1,high=5)

In [85]:
print(m)
print(n)

tensor([[4, 3, 2],
        [2, 3, 4]])
tensor([[3, 1, 4],
        [1, 3, 1]])


In [86]:
m+n # The results are not stored anywhere

tensor([[7, 4, 6],
        [3, 6, 5]])

In [87]:
m.add_(n)  #Stores the result in tensor m

tensor([[7, 4, 6],
        [3, 6, 5]])

In [88]:
m

tensor([[7, 4, 6],
        [3, 6, 5]])

In [89]:
m.relu_() #Applies relu function and stores the result in tensor 'm' .. Here "_" represents inplace

tensor([[7, 4, 6],
        [3, 6, 5]])

# Copying a tensor

In [90]:
o = torch.rand(2,3)
o

tensor([[0.2700, 0.1576, 0.8879],
        [0.9792, 0.2627, 0.1800]])

In [91]:
# If we do the traditional approach that we do in python like this :
p=o
# This will create a new tensor 'p' referencing to the same memory of 'o'. So if we make change in p then the change will also be in o
p[0][0]=9
print(p)
print(o)

tensor([[9.0000, 0.1576, 0.8879],
        [0.9792, 0.2627, 0.1800]])
tensor([[9.0000, 0.1576, 0.8879],
        [0.9792, 0.2627, 0.1800]])


In [92]:
id(o) ## Memory location of 'O'

138245882285904

In [93]:
id(p) ## Memory location of 'P'

138245882285904

In [94]:
# To copy a tensor , This create a new tensor 'q' in seperate memory location
q = o.clone()

In [95]:
id(q)

138245882289648

# Tensor operation in GPU

In [96]:
torch.cuda.is_available() #Check is Gpu is available


True

In [98]:
device=torch.device('cuda')

In [101]:
# Creating a new tensor on GPU
r = torch.rand((2,3),device=device)
r

tensor([[0.4674, 0.2601, 0.3044],
        [0.9964, 0.8242, 0.1826]], device='cuda:0')

In [102]:
# Moving an existing tensor(i.e on CPU) to GPU
a

tensor([[0.5479, 0.4440, 0.7041],
        [0.5573, 0.6959, 0.9849]])

In [105]:
b=a.to(device=device) # Move existing tensor 'a' to Gpu and store to new variable b
b

tensor([[0.5479, 0.4440, 0.7041],
        [0.5573, 0.6959, 0.9849]], device='cuda:0')

In [ ]:
import time
time.time()

1739889150.4309537